### ISSUE TITLE
Long image pull on first run can fail test

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/integration-tests#145]
# Intro
If we run test on a cluster without test images already pulled, k8s starts pulling images during the test.

# Issue
First run of a test on cluster possibly can fail due to the NSC request/dial timeout if NSC image starts before k8s have pulled all other images.

# Possible solutions

## Image prefetching
We can add image prefetching before running integration tests on cluster.

Pros:
* all test runs are very similar to each other because we don't have long first test run

Cons:
* if someone wants to run our tests locally, there will be a need to pull images before testing

## Increasing request/dial timeouts

Pros:
* everyone can just copy-paste our tests and there will be no problems with it

Cons:
* we don't actually need such huge timeouts for the tests, we need them only for images pulling, won't it affect tests efficiency?

**Comment by denis-tingaikin** [comment]
I like the option with `Increasing request/dial timeouts`. 
@edwarnicke What do you think?

**Comment by edwarnicke** [comment]
Hmm...  how long are we seeing for image pulls?

**Comment by Bolodya1997** [comment]
~20 seconds to pull NSC+NSE for the kernel test on kind on CI.
~40 seconds to pull NSC+NSE for the VFIO test on packet on CI.

**Comment by edwarnicke** [comment]
@Bolodya1997  Are we hitting timeouts on the *tests* or timouts on the NSC Requests?

**Comment by Bolodya1997** [comment]
I have had NSC Request timeouts hit locally on kind tests. So there was 1+ minute for images pulling :)

**Comment by denis-tingaikin** [comment]
I did not see timeouts on the kind yet, 

We can just increase the timeout for requests if we face this kind of issues

**Comment by denis-tingaikin** [comment]
> ~20 seconds to pull NSC+NSE for the kernel test on kind on CI.
> ~40 seconds to pull NSC+NSE for the VFIO test on packet on CI.

Did you check only cmd-nsc and cmd-icmp-responder-nse?

**Comment by edwarnicke** [comment]
@denis-tingaikin I'm reluctant to blindly increase timers, because we want to make sure we stay *fast* for the response of the system to failure.  Particularly as we get into healing, we want to make sure our healing behavior (as distinct from image download) is very very fast.

**Comment by edwarnicke** [comment]
Any further thoughts on this?

**Comment by Bolodya1997** [comment]
Since we are not yet facing this issue on CI we probably can do nothing and wait for this to become an actual problem.
There is a problem for me when I am running kind tests locally, but it doesn't actually affect anything because it can be easily fixed locally by manual prefetching.
Probably it can become an issue if someone else will meet this locally, so I guess we should just wait :)

**Comment by edwarnicke** [comment]
@Bolodya1997 Sounds good... lets keep an eye on it :)

**Comment by denis-tingaikin** [comment]
@edwarnicke The issue still actual we got timeouts on GKE: https://github.com/networkservicemesh/integration-k8s-gke/pulls

Currently, we have the next options:
1. Add prefetching of images on the testing level.
2. Add prefetching of images on deployments-k8s level (For example as an separate markdown file with prefetching instructions).
3. Increase timeouts on wait for status ready from 1m --> 2m.
4. Your option.

Options: 1, 3 looks good to me.

**Comment by edwarnicke** [comment]
I'd rather prefetch the images than increase the timers.
