### ISSUE TITLE
Logs are not collected from clusters

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/integration-tests#2706]
Probably related to this fix: https://github.com/networkservicemesh/integration-tests/pull/2692

### Incidents 
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/4789367878
https://github.com/networkservicemesh/integration-k8s-aws/actions/runs/4790447140

Pay attention to the GKE cluster. It seems that the logs from it is not collected for a long time
https://github.com/networkservicemesh/integration-k8s-gke/actions/runs/4790447401
https://github.com/networkservicemesh/integration-k8s-gke/actions/runs/4656954257

**Comment by NikitaSkrynnik** [comment]
## Definition on done
Integration tests: Logs are collected and can be accessed after each CI run in Artifacts section
GKE: Logs are collected and can be accessed after each CI run in Artifacts section
