### ISSUE TITLE
Run integration tests in parallel

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/integration-tests#2862]
## Description
We need to run the rest of integration tests in parallel

## Decomposition

| Subtask | Estimation | Spent | Status |
| ----------- | -------------- | -------- | -------- |
| Run Heal Tests in parallel | 5h | 6.5h | Done |
| Run Rvlan Tests in parallel | 14h | 18 h | Done |
| Run Interdomain tests in parallel | 14h | 3.5h |  |
| Try to increase count of workers for parallel tests | 3h | | |
| Test on public clusters and tune a number of tests that could be run in parallel | 4h | | |
| Risks | 14h | |

**Comment by denis-tingaikin** [comment]
Seems like done. As we found its dificult to parallel heal tests.
