### ISSUE TITLE
No artifacts after CI run on public clusters

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/integration-tests#2874]
## Links
- https://github.com/networkservicemesh/integration-k8s-gke/actions/runs/5619508780
- https://github.com/networkservicemesh/integration-k8s-aws/actions/runs/5657007438
- https://github.com/networkservicemesh/integration-interdomain-k8s/actions/runs/5619510871

**Comment by denis-tingaikin** [comment]
Seems like fixed
