### ISSUE TITLE
Consider testing on ARM64 machines

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-tests#3390]
Currently, NSM supports ARM64 image building, but we're not running tests on ARM64-based machines. To improve scenario coverage, we need to consider adding a new repo or editing an existing one for testing our scenario on ARM64 machines.

## Defenition of done

1. Consider the cluster provider with arm64 machines
2. Suggest options of implementation (edit some of integration testing repo or add a new one)
3. Add testing on arm64
4. Make sure that all test work as expected.
5. If some of tests are not working feel free to disable them and open a ticket for each unstable scenario.

## Context

https://github.com/networkservicemesh/deployments-k8s/issues/10985
https://github.com/networkservicemesh/deployments-k8s/issues/9215

**Comment by glazychev-art** [comment]
### Options
**1. Github `macos-14` runner (free)**
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
Github has provided a beta version of macos-14 for use (M1).
```
Virtual Machine 	Processor (CPU) 	Memory (RAM) 	Storage (SSD) 	OS (YAML workflow label)
macOS 	                         3 (M1) 	        7 GB 	   14 GB 	   macos-14 [Beta] 	
```
**Pros:** it's free
**Cons:** possible lack of resources


**2. Github `macos-xlarge` runner**
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners
```
Runner Size	Architecture	Processor (CPU)	       Memory (RAM)	Storage (SSD)	YAML workflow label
XLarge	         arm64 (M1)	6 CPU and 8 GPU	        14 GB	         14 GB	          macos-latest-xlarge, macos-13-xlarge[latest], macos-14-xlarge[Beta]
```
**Pros:** more resources
**Cons:** involves payment
Billing - https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates

**3. Equinix metal**
https://deploy.equinix.com/product/servers/c3-large-arm64/
Equinix metal has  `c3.large.arm64`
**Pros:** 
- a lot of resources
- bare metal

**Cons:** additional configuration may be required when using the cluster API.

**4. GKE**
GKE provides Tau T2A machine series
We could start with `t2a-standard-2`
https://cloud.google.com/compute/docs/general-purpose-machines#t2a_machines
**Pros:** k8s cluster provider
**Cons:** involves payment

**Comment by glazychev-art** [comment]
@denis-tingaikin @edwarnicke 
I would suggest using Equinix Metal. What do you think?

**Comment by denis-tingaikin** [comment]
Seems like done.
