### ISSUE TITLE
Refactor "parallel" package with passing excludedTests via Options

### ISSUE THREAD

**Issue by VitalyGushin** [networkservicemesh/integration-tests#3510]
Package: "github.com/networkservicemesh/integration-tests/extensions/parallel"

Proposed changes:
<img width="788" alt="Screenshot 2024-03-07 at 14 50 59" src="https://github.com/networkservicemesh/integration-tests/assets/44492771/711d58f1-4166-478f-a723-cb37f7b97bb5">

**Comment by denis-tingaikin** [comment]
It's done. Thanks
