### ISSUE TITLE
Spec: markdown based integration tests

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-tests#4]
Spec: https://docs.google.com/document/d/1fslGWT0ZzEzycaTA0-HbVl9yLuH9cPBRza0Rshp7pTI/edit?usp=sharing

**Comment by denis-tingajkin** [comment]
@edwarnicke , @haiodo , @fkautz  Can we go with this? Please share your thoughts

**Comment by haiodo** [comment]
I'd like this approach, left few comments on spec.

**Comment by denis-tingaikin** [comment]
Done: https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/basic
