### ISSUE TITLE
SR-IOV tests are failing on packet

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/integration-tests#409]
### CI run
https://github.com/networkservicemesh/integration-k8s-packet/runs/2497956946?check_suite_focus=true
### Logs
[logs-493.zip](https://github.com/networkservicemesh/integration-tests/files/6419806/logs-493.zip)

**Comment by edwarnicke** [comment]
@Bolodya1997 Any idea why yet?

**Comment by denis-tingaikin** [comment]
@edwarnicke, @Bolodya1997 It looks like the packet is working https://github.com/networkservicemesh/integration-k8s-packet/pull/49

I guess it is fixed by https://github.com/networkservicemesh/integration-k8s-kind/issues/197

So closing this.
