### ISSUE TITLE
Test ExampleReteriveList fails on ci

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/integration-tests#989]
## Description
ExampleReteriveList sometimes fails on ci on macOS
It is not reproducible locally and require additional investigation.

## Logs
example of failed build: https://github.com/networkservicemesh/integration-tests/runs/4089348510?check_suite_focus=true#step:5:10

**Comment by denis-tingaikin** [comment]
Fixed in https://github.com/networkservicemesh/integration-tests/commit/79815bb6a452a580ef6ba82ecb7e0706f6bc0caf
